###############################################################################
#
#  Generated by José W. R. Pereira : AVR on Arduino 
#  
###############################################################################

PROJECT_NAME := projeto
CC := avr-gcc
MCU := atmega328p
COM_PORT := /dev/ttyACM0
CLOCK := 16000000UL 

###############################################################################

C_SRCS += \
atraso.c \
main.c

OBJS += \
atraso.o \
main.o

###############################################################################

all:	HEX
	avr-size --format=avr --mcu=$(MCU) $(PROJECT_NAME) 

HEX:	OBJ
	avr-objcopy -O ihex -R .eeprom $(PROJECT_NAME) $(PROJECT_NAME).hex

OBJ: GCC
	$(CC) -mmcu=$(MCU) $(OBJS) -o  $(PROJECT_NAME)

GCC: $(OBJS)
	
$(OBJS): $(C_SRCS)
	$(CC) -Os -DF_CPU=$(CLOCK) -mmcu=$(MCU) -c -o $@ $(subst .o,.c,$@)

###############################################################################

usb: tty
	ls /dev/ttyACM*
tty: 
	dmesg | grep tty

grava: 
	avrdude -p m328p -c arduino -P $(COM_PORT) -U flash:w:$(PROJECT_NAME).hex:a

grava2:
	avrdude -F -V -c arduino -p $(MCU) -P $(COM_PORT) -b 115200 -U flash:w:$(PROJECT_NAME).hex

###############################################################################

clean: $(OBJS)
	rm -f $(OBJS)
	rm -f $(PROJECT_NAME)
	rm -f $(PROJECT_NAME).hex


##############################################################################
##############################################################################
